version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "org.jetbrains.kotlin*"
      - dependency-name: "io.papermc.paper*"

    reviewers:
      - peco2282


  - package-ecosystem: "gradle"
    directory: "/TestPlugin"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "test-plugin"
    ignore:
      - dependency-name: "org.jetbrains.kotlin*"
      - dependency-name: "io.papermc.paper*"
    reviewers:
      - peco2282

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - peco2282
